steps:

- name: 'list-files'
  script: |
    #!/usr/bin/env bash
    ls -l

- name: 'build'
  script: |
    #!/usr/bin/env bash
    echo "Build Started"
    echo "Build done"

- name: 'test'
  script: echo "Tests running"
  
- name: 'deployment'
  script: |
    #!/usr/bin/env bash
    echo "Deployment Started"
    echo "Deployment done"

logsBucket: 'gs://gds-log-bucket'
options:
  logging: GCS_ONLY
